# Generated by Django 5.0.2 on 2024-05-16 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('watched', models.BooleanField(default=False)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('up_votes', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=250, null=True)),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('actors', models.CharField(blank=True, max_length=250, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='film_festival.film')),
            ],
        ),
    ]
