# Generated by Django 5.0.2 on 2024-05-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('watched', models.BooleanField(default=False)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('up_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_festival.film')),
            ],
        ),
    ]
