# Generated by Django 5.0.2 on 2024-05-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='film_festival.film'),
        ),
    ]
