# Generated by Django 5.0.2 on 2024-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0003_rename_up_votes_film_total_upvotes_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
