# Generated by Django 5.0.2 on 2024-05-15 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0004_film_actors_film_director_film_genre_film_imdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
