# Generated by Django 5.0.2 on 2024-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0005_film_proposed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='providers',
            field=models.ManyToManyField(related_name='films', to='film_festival.provider'),
        ),
    ]
