# Generated by Django 5.0.2 on 2024-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0005_film_created_film_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
