# Generated by Django 5.0.2 on 2024-05-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0006_provider_film_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='film_festival.genre'),
        ),
    ]
