# Generated by Django 5.0.2 on 2024-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0007_genre_film_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='films', to='film_festival.provider'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
