# Generated by Django 5.0.2 on 2024-05-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0008_alter_film_providers_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
