# Generated by Django 5.0.2 on 2024-03-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studies',
            new_name='Studie',
        ),
    ]
