# Generated by Django 5.0.1 on 2024-03-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
