# Generated by Django 5.0.1 on 2024-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('job_tasks', models.JSONField()),
                ('skills', models.ManyToManyField(to='base.technicalskill')),
            ],
        ),
    ]
