# Generated by Django 5.0.1 on 2024-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='current_work',
            field=models.BooleanField(default=False),
        ),
    ]
