# Generated by Django 5.0.1 on 2024-03-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='skills',
            field=models.ManyToManyField(to='base.technicalskill'),
        ),
    ]
