# Generated by Django 5.0.2 on 2024-03-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studie',
            new_name='Study',
        ),
    ]
