# Generated by Django 5.0.1 on 2024-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studies_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='skills',
            field=models.ManyToManyField(blank=True, to='base.technicalskill'),
        ),
    ]
