# Generated by Django 5.0.1 on 2024-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_workexperience_current_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
