# Generated by Django 5.0.1 on 2024-02-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_technicalskill_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskillcategory',
            name='skills',
            field=models.ManyToManyField(related_name='categories', to='base.technicalskill'),
        ),
    ]
