# Generated by Django 5.0.1 on 2024-02-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_technicalskillcategory_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalskill',
            name='category',
        ),
    ]
