# Generated by Django 5.0.2 on 2024-03-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalskill',
            name='rating',
        ),
    ]
