# Generated by Django 5.0.1 on 2024-02-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_technicalskill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.technicalskillcategory'),
        ),
    ]
