# Generated by Django 5.0.2 on 2024-03-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_technicalskill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
