# Generated by Django 5.0.1 on 2024-02-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_technicalskill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalskill',
            name='category',
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='categories',
            field=models.ManyToManyField(related_name='skill_skills', to='base.technicalskillcategory'),
        ),
        migrations.AlterField(
            model_name='technicalskillcategory',
            name='skills',
            field=models.ManyToManyField(related_name='skill_categories', to='base.technicalskill'),
        ),
    ]
