# Generated by Django 5.0.2 on 2024-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_technicalskill_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskillcategory',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
