# Generated by Django 5.0.1 on 2024-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_technicalskill_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskill',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='skill_skills', to='base.technicalskillcategory'),
        ),
    ]
