# Generated by Django 5.0.2 on 2024-03-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_study_created_study_updated_project_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tittle',
            new_name='title',
        ),
    ]
