# Generated by Django 5.0.1 on 2024-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_technicalskill_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
