# Generated by Django 5.0.2 on 2024-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_tittle_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
