# Generated by Django 5.0.2 on 2024-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_project_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
    ]
